### ISSUE TITLE
assets 폴더 만들어서 svg, 이미지 한번에 import 하기

### ISSUE THREAD

**Issue by NamJwong** [SOPTerest/Client#14]
## ✨ 어떤 기능인가요?
assets 폴더 만들어서 svg, 이미지 한번에 import 하기

참고하기 -> https://github.com/Neogasogaeseo/Naega-Web/tree/dev/src/assets

## ✅ To Dos

- [ ] assets 폴더 만들어서 svg, 이미지 한번에 import 하기

**Comment by NamJwong** [comment]
서영이 헤더 pr에서 svg를 처음썼나? 그런거면 그 pr 머지되고 해야할듯요!

**Comment by leeseooo** [comment]
제가 svg 정리해서 pr 다시 업데이트 하겠습니다!
