### ISSUE TITLE
라우팅 바뀐 뷰에 맞춰서 다시 하기

### ISSUE THREAD

**Issue by NamJwong** [SOPTerest/Client#8]
## ✨ 어떤 기능인가요?
라우팅 바뀐 뷰에 맞춰서 다시 하기 (Board 컴포넌트 PR 머지되면)

MyPage -> /
BoardForm -> /create
Board -> /board/:id

## ✅ To Dos

- [x] 라우팅 바뀐 뷰에 맞춰서 다시 하기

**Comment by NamJwong** [comment]
손 남는 사람 아무나 하면 될 것 같습니다 ~! ~!

**Comment by aeuna** [comment]
제가 하겠습니다!!
